### ISSUE TITLE
Compiling issue with 'Microsoft.Azure.NotificationHubs.CDataMember'

### ISSUE THREAD

**Issue by Martin-Stein** [Azure/azure-notificationhubs-dotnet#111]
Hi there,

I have an UWP Project, that is using Notificationhub.
When I compile my code in debug mode (x86) everything works fine.
When I try to create a store package the compilation fails  for configuration release x86 with error:

"System.Runtime.Serialization.InvalidDataContractException: Type 'Microsoft.Azure.NotificationHubs.CDataMember' does not have a static method 'GenerateSchema' that takes a parameter of type 'System.Xml.Schema.XmlSchemaSet' as specified by the XmlSchemaProviderAttribute attribute."

I am using VS2019 Version 16.4.2
Nuget Package is: Microsoft.Azure.NotificatioHubs Version 3.3.0

What causes this isssue??

Kind regards,

Martin

**Comment by Martin-Stein** [comment]
Hi,
I have played a litte bit around and it turns out, when I have WindowsAzure.Messaging.Managed and Microsoft.Azure.NotificationHubs Nuget-packages in my project, I am not able to compile in release configuration. Even if no line of code is involved. It is enough to have the Nuget-packages in my references to produce the error above!

Best regards,

Martin

**Comment by Grzesik** [comment]
Hi, I have the same problem. Do you have any solution? I can't go to the store because of this error.
The Microsoft.Azure.NotificationHubs Nuget package has the version 3.3.0 (the latest).




3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error : System.Runtime.Serialization.InvalidDataContractException: Type 'Microsoft.Azure.NotificationHubs.CDataMember' does not have a static method 'GenerateSchema' that takes a parameter of type 'System.Xml.Schema.XmlSchemaSet' as specified by the XmlSchemaProviderAttribute attribute.
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.SchemaExporter.InvokeSchemaProviderMethod(Type clrType, XmlSchemaSet schemas, XmlQualifiedName& stableName, XmlSchemaType& xsdType, Boolean& hasRoot)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.SchemaExporter.GetXmlTypeInfo(Type type, XmlQualifiedName& stableName, XmlSchemaType& xsdType, Boolean& hasRoot)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.XmlDataContract.XmlDataContractCriticalHelper..ctor(Type type)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.XmlDataContract..ctor(Type type)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Type type)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Type type)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.DataMember.CriticalHelper.get_MemberTypeContract()
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.DataMember.Equals(Object other, Dictionary`2 checkedContracts)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.ClassDataContract.Equals(Object other, Dictionary`2 checkedContracts)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.DataContract.Equals(Object other)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Collections.Generic.Dictionary`2.ContainsValue(TValue value)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Collections.Generic.Dictionary`2.ValueCollection.System.Collections.Generic.ICollection<TValue>.Contains(TValue item)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at SerializationAssemblyGenerator.Program.GenerateDataContractSerializerHelperCode(IEnumerable`1 contracts, IEnumerable`1 jsonContracts, IEnumerable`1 wcfSerializers)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at SerializationAssemblyGenerator.Program.GenerateDataContractSerializerHelper(IEnumerable`1 contracts, IEnumerable`1 jsonContracts, GeneratorSettings settings, String intermediateAssembly, IEnumerable`1 wcfSerializers)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at SerializationAssemblyGenerator.Program.Main(String[] args)

**Comment by ncunning** [comment]
Same issue. Can't build for release. Anyone found a workaround for store submission?

**Comment by stankovski** [comment]
Why do you need `WindowsAzure.Messaging.Managed` nuget package? If you need it for ServiceBus, can you use https://www.nuget.org/packages/Microsoft.Azure.ServiceBus package instead?

**Comment by ncunning** [comment]
@stankovski The documentation says to use it. https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-windows-store-dotnet-get-started-wns-push-notification#create-a-sample-windows-app

Step 8

**Comment by stankovski** [comment]
This looks like a doc issue. You should not need the `WindowsAzure.Messaging.Managed` nuget package.

**Comment by ncunning** [comment]
@stankovski I have raised a query https://github.com/MicrosoftDocs/azure-docs/issues/51148

But this Line here:
var hub = new NotificationHub("<your hub name>", "<Your DefaultListenSharedAccessSignature connection string>");
    
On peeking into the code uses:

#region Assembly Microsoft.WindowsAzure.Messaging.Managed, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// 
#endregion

using Microsoft.WindowsAzure.Messaging;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Windows.Data.Xml.Dom;

namespace Microsoft.WindowsAzure.Messaging
{
    public sealed class NotificationHub : Entity
    {
        public NotificationHub(string notificationHubPath, string connectionString);

**Comment by Grzesik** [comment]
I use it also, because I have an Xamarin.Forms App. The same Nuget Package is used for iOS, Android and UWP.

**Comment by ncunning** [comment]
@Grzesik One thing i did find was that i can get it to build/compile in release mode. Notification Hub still doesn't work so kinda pointless:

WITH THE NATIVE TOOLCHAIN ENABLED FOR x86, x64 and ARM:

So i added:
                    typeof(Windows.Networking.PushNotifications.PushNotificationChannel).GetTypeInfo().Assembly,
                typeof(Microsoft.WindowsAzure.Messaging.DataContractBinarySerializer).GetTypeInfo().Assembly,

The the assembliesToInclude
Xamarin.Forms.Forms.Init(e, assembliesToInclude);

And now it builds/compiles. However i see alot of WindowsAzure.Messaging.Managed Exceptions of <unkown> being thrown and obviously notifications don't work or register with the PushNotificationChannelManager.

**Comment by Grzesik** [comment]
@ncunning I've tried it, but I get still an error in Release mode::

  Processing application code
3>  Computing application closure and generating interop code
3>    Loading 199 modules...
3>    Generating code...
3>    Interop code generated.
3>  Generating serialization code
3>  Compiling interop code
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error : System.Runtime.Serialization.InvalidDataContractException: Type 'Microsoft.Azure.NotificationHubs.CDataMember' does not have a static method 'GenerateSchema' that takes a parameter of type 'System.Xml.Schema.XmlSchemaSet' as specified by the XmlSchemaProviderAttribute attribute.
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.SchemaExporter.InvokeSchemaProviderMethod(Type clrType, XmlSchemaSet schemas, XmlQualifiedName& stableName, XmlSchemaType& xsdType, Boolean& hasRoot)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.SchemaExporter.GetXmlTypeInfo(Type type, XmlQualifiedName& stableName, XmlSchemaType& xsdType, Boolean& hasRoot)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.XmlDataContract.XmlDataContractCriticalHelper..ctor(Type type)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.XmlDataContract..ctor(Type type)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Type type)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Type type)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.DataMember.CriticalHelper.get_MemberTypeContract()
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.DataMember.Equals(Object other, Dictionary`2 checkedContracts)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.ClassDataContract.Equals(Object other, Dictionary`2 checkedContracts)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Runtime.Serialization.DataContract.Equals(Object other)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Collections.Generic.Dictionary`2.ContainsValue(TValue value)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Collections.Generic.Dictionary`2.ValueCollection.System.Collections.Generic.ICollection<TValue>.Contains(TValue item)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at SerializationAssemblyGenerator.Program.GenerateDataContractSerializerHelperCode(IEnumerable`1 contracts, IEnumerable`1 jsonContracts, IEnumerable`1 wcfSerializers)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at SerializationAssemblyGenerator.Program.GenerateDataContractSerializerHelper(IEnumerable`1 contracts, IEnumerable`1 jsonContracts, GeneratorSettings settings, String intermediateAssembly, IEnumerable`1 wcfSerializers)
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error :    at SerializationAssemblyGenerator.Program.Main(String[] args)
3>  Generating System.Reflection.DispatchProxy proxy code.
3>C:\Users\Marian.GRZESIK\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error : ILT0032: Failed to compile serialization code. See the build log for error details.

**Comment by stankovski** [comment]
I have updated the UWP sample and have verified that the latest version of the https://www.nuget.org/packages/Microsoft.Azure.NotificationHubs package works and compiles under Release configuration.

As far as usage you would need to update the code to something like:

```
            var hub = new NotificationHubClient(Secrets.HubName, Secrets.HubConnectionString);
            await hub.CreateOrUpdateInstallationAsync(new Installation
            {
                Platform = NotificationPlatform.Wns,
                InstallationId = "myid",
                PushChannel = channel.Uri
            });
```

https://github.com/Azure/azure-notificationhubs-dotnet/pull/119

**Comment by Grzesik** [comment]
Hi @stankovski, I've tested your sample and it works. Unfortunatelly it doesn't change my problem. But I've underestood, what the reason for the problem is. 
I created the NotificationHub for iOS, Android and Uwp, like described here: 

https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-windows-store-dotnet-get-started-wns-push-notification

The problem ist the WindowsAzure.Messaging.Managed Nuget Package, which cause the problem, when linking in realse mode. 

It is possible to update that package?

**Comment by stankovski** [comment]
We are working on updating our SDK to include functionality available in WindowsAzure.Messaging.Managed however you should be able to get your app working with just NotificationHubClient. What functionality are you currently missing?

**Comment by stankovski** [comment]
Not sure what you mean by 
>cant find my NotificationHubName

Also your line `var hub = new NotificationHubClient(AppConstants.NotificationHubName, AppConstants.NotificationHubDefaultListenSharedAccessSignature);` has parameters flipped. The first parameter is the connection string and the second one is the hub name.

**Comment by stankovski** [comment]
As mentioned above (https://github.com/Azure/azure-notificationhubs-dotnet/issues/111#issuecomment-606148344), you should just use installation API (https://docs.microsoft.com/en-us/archive/msdn-magazine/2015/april/microsoft-azure-azure-notification-hubs-best-practices-for-managing-devices#registering-devices). It will allow you to create or update a registration with the channel. There is no need to delete registrations all the time.

**Comment by Grzesik** [comment]
Hi @stankovski , if I change the parameters in the NotificationHubClient, I get an Exception too:

Message = "The remote server returned an error: (401) Unauthorized. Reason: ..TrackingId:8a7dd317-575c-4429-8b73-675a9d73c156,TimeStamp:2020-04-06T05:56:47.5365128Z"

1. The Managed version of the library (from 2014) as in my and your link shows, work wery well. It cause only the problem in release mode and can't be copied to the store
2. I have to unregister and new register the token and tag, because in login it can be an another credential, which use an another tag.
