### ISSUE TITLE
UnauthorizedAccessException: ExpiredToken after 20min

### ISSUE THREAD

**Issue by BertrandJU** [Azure/azure-notificationhubs-dotnet#12]
Hello, 
I have an issue with Microsoft.Azure.NotificationHubs v2.0.1 
Under heavy usage, after 20min, I systematically get exception "System.UnauthorizedAccessException: ExpiredToken" 
After investigation I found an issue in Microsoft.Azure.NotificationHubs.Auth.TokenProvider.TrySetIntoCache : there is a SlidingExpiration even though the token is absolutely expired in 20min ( Microsoft.Azure.NotificationHubs.Auth.SharedAccessSignatureTokenProvider.DefaultTokenTimeout )
So it lacks an AbsoluteExpiration with the same ExpirationDate as the token.

_My logs:_ 
`EXCEPTION:System.UnauthorizedAccessException:  ExpiredToken: .TrackingId:fa5e49c9-330d-4f0e-9bb8-58360f9a4e37_G7,TimeStamp:11/13/2018 4:05:33 PM
   at Microsoft.Azure.NotificationHubs.NotificationHubClient.SendRequestAsync(HttpRequestMessage request, String trackingId, HttpStatusCode[] successfulResponseStatuses, CancellationToken cancellationToken)
   at Microsoft.Azure.NotificationHubs.NotificationHubClient.SendRequestAsync(HttpRequestMessage request, String trackingId, HttpStatusCode successfulResponseStatus, CancellationToken cancellationToken)
   at Microsoft.Azure.NotificationHubs.NotificationHubClient.GetAllEntitiesImplAsync[TEntity](UriBuilder requestUri, String continuationToken, Int32 top, CancellationToken cancellationToken)
   at NotificationHub.API.BusinessCommands.RegisterMobileDeviceCommand.ExecuteAsync()`

_A dirty workaround until fix is to disable token caching (using Reflection):_
`var tokenProviderField = typeof(Microsoft.Azure.NotificationHubs.NotificationHubClient).GetField("_tokenProvider", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);
var tokenProvider = tokenProviderField.GetValue(client);
var tokenProvider_cacheTokensField = tokenProvider
                                    .GetType() //Microsoft.Azure.NotificationHubs.Auth.SharedAccessSignatureTokenProvider
                                    .BaseType //Microsoft.Azure.NotificationHubs.Auth.TokenProvider
                                    .GetField("_cacheTokens", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);
tokenProvider_cacheTokensField.SetValue(tokenProvider, false);`

this bug may be related to #9 
I will submit a PR.
Thanks

**Comment by mpodwysocki** [comment]
@BertrandJU closed as per #13
