### ISSUE TITLE
Unable to set priority for FCM templated messages

### ISSUE THREAD

**Issue by stpatrick2016** [Azure/azure-notificationhubs-dotnet#176]
**Describe the bug**
In order to set priority for FCM messages, one needs to declare the *priority* tag on the same level as the *data* tag or, in the [latest version](https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message) it should be under the *android* tag. When using *FcmTemplateRegistrationDescription* with such template, an exception *System.Xml.XmlException: There are multiple root elements* is raised though. 

***Exception or Stack Trace***
```
System.AggregateException: One or more errors occurred. (There are multiple root elements.)
 ---> System.Xml.XmlException: There are multiple root elements.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, String res, String arg1, String arg2, String arg3)
   at System.Xml.XmlBaseReader.EnterScope()
   at System.Runtime.Serialization.Json.XmlJsonReader.ReadNonExistentElementName(StringHandleConstStringType elementName)
   at System.Runtime.Serialization.Json.XmlJsonReader.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at Microsoft.Azure.NotificationHubs.FcmTemplateRegistrationDescription.OnValidate()
   at Microsoft.Azure.NotificationHubs.RegistrationDescription.Validate(Boolean checkExpirationTime)
   at Microsoft.Azure.NotificationHubs.RegistrationSDKHelper.ValidateRegistration(RegistrationDescription registration)
   at Microsoft.Azure.NotificationHubs.NotificationHubClient.CreateOrUpdateRegistrationImplAsync[TRegistration](TRegistration registration, EntityOperatonType operationType, CancellationToken cancellationToken)
```

**To Reproduce**
1. Create *FcmTemplateRegistrationDescription* with template like this:
```
{
    "data":{
        "message":"$(message)",
    },
    "priority":"high"
}
```
2. Call *CreateOrUpdateRegistrationAsync*

***Code Snippet***
The code snippet that causes the issue.
```csharp
var hub = NotificationHubClient.CreateClientFromConnectionString("put your connection string here", "your hub name");
var registration = new FcmTemplateRegistrationDescription(token, @"
            {
	            ""data"":{
		            ""message"":""$(message)"",
	            },
	            ""priority"":""high""
            }");
registration.RegistrationId = await hub.CreateRegistrationIdAsync();
await hub.CreateOrUpdateRegistrationAsync(registration); //will raise exception
```

**Expected behavior**
The template should be accepted, or there should be another option to set properties such as priority (or any other of the dozens of properties)

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio 2019
 - Version of the Library used: 4.1.0

**Additional context**
I believe the problem lies in the *FcmTemplateRegistrationDescription.OnValidate*, [line 294](https://github.com/Azure/azure-notificationhubs-dotnet/blob/d203f2b0c6cafb07b8f1e799c6983423f34c811e/src/Microsoft.Azure.NotificationHubs/AndroidTemplateRegistrationDescription.cs#L294), which explicitly requires to have only 1 root.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by stpatrick2016** [comment]
Actually looks like I have found the problem - the error returned by XmlReader is misleading. The problem was in the extra comma after the *message* tag. Removing it it has worked as expected. Took me half day to figure out and only saw that **after** re-reading this post.
Closing the issue - misleading error is not relevant to this library anyway.
