### ISSUE TITLE
[BUG] "The supplied notification payload is invalid." when using Apple sound dictionary rather than sound string.

### ISSUE THREAD

**Issue by tracy-hunt** [Azure/azure-notificationhubs-dotnet#194]
**Describe the bug**
In an Apple notification, when using the sound *dictionary* rather than the sound *string* (https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification#2990112), the hub (SendDirectNotificationAsync) throws an exception.

***Exception or Stack Trace***
   at Microsoft.Azure.NotificationHubs.NotificationHubClient.<SendRequestAsync>d__201.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.NotificationHubs.NotificationHubClient.<>c__DisplayClass189_0.<<SendNotificationImplAsync>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.NotificationHubs.NotificationHubRetryPolicy.<RunOperation>d__4`1.MoveNext()
   at Microsoft.Azure.NotificationHubs.NotificationHubRetryPolicy.<RunOperation>d__4`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.NotificationHubs.NotificationHubClient.<SendNotificationImplAsync>d__189.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AzureHubsDebug.Form2.<button1_Click>d__2.MoveNext() in C:\_git\app-admintools\DebugPushApp\AzureHubWinFormsDebug\AzureHubsDebug\Form2.cs:line 39

**To Reproduce**
Create an Apple notification and replace the sound string with a sound dictionary as per the Apple documentation linked above.

***Code Snippet***
The following sound string works:
`
{
    "aps":{
        "alert":{
            "body":"message body",
            "title":"message title"
        },
        "sound":"custom_sound.wav"
    }
}
`

The following sound dictionary does not work:
`
{
    "aps":{
        "alert":{
            "body":"message body",
            "title":"message title"
        },
        "sound":{
            "critical": 1,
            "name":"custom_sound.wav",
            "volume": 1.0
        }
    }
}
`

**Expected behavior**
Azure hubs should accept sound as either a string or a dictionary as per the Apple documentation linked above.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - IDE : Visual Studio 2019 v 16.9.5
 - Version of the Library used: Microsoft.Azure.NotificationHubs v 4.1.0

**Additional context**
N/A

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by mpodwysocki** [comment]
@tracy-hunt This is a known issue with our system as we do not support critical alerts yet, however, it is on the roadmap.

**Comment by mpodwysocki** [comment]
@tracy-hunt This should now be closed as critical sound is now supported.
